In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = [
    ["CSCI 175", "Freshman", 3, "No", "Neither", 3],
    ["CSCI 175", "Sophomore", 3, "No", "Neither", 1],
    ["CSCI 175", "Freshman", 3, "No", "Neither", 1],
    ["DTSC 320", "Senior", 3, "No", "Neither", 2],
    ["Math 107", "Junior", 3, "No", "Wrting", 3],
    ["MATH 160", "Sophomore", 3, "No", "Neither", 2],
    ["MATH 161", "Sophomore", 3, "No", "Neither", 3],
    ["MATH 240", "Freshman", 3, "No", "Neither", 2],
    ["CSCI 175", "Freshman", 3, "No", "Neither", 1],
    ["SOWK 110", "Sophomore", 3, "No", "Wrting", 0],
    ["CSCI 175", "Freshman", 3, "No", "Neither", 1],
    ["INST 150", "Freshman", 3, "No", "Neither", 0],
    ["CSCI 175", "Junior", 3, "No", "Neither", 1],
    ["ENGL 102", "Freshman", 3, "No", "Neither", 2],
    ["MATH 221", "Freshman", 3, "No", "Neither", 0],
    ["CSCI 405", "Senior", 3, "No", "Neither", 1],
    ["Math 160", "Freshman", 3, "No", "Neither", 3],
    ["INST 150", "Freshman", 3, "No", "Neither", 1],
    ["MATH 160", "Freshman", 3, "No", "Neither", 2],
    ["CSCI 175", "Sophomore", 3, "No", "Neither", 0],
    ["DTSC 380", "Senior", 3, "No", "Neither", 1],
    ["Psyc 205", "Sophomore", 3, "No", "Neither", 8],
    ["CSCI 175", "Sophomore", 3, "Yes", "Neither", 2],
    ["DTSC 320", "Senior", 3, "No", "Neither", 4],
    ["MISS 100", "Sophomore", 3, "No", "Reading", 2],
    ["MUSI 145", "Senior", 2, "No", "Neither", 1],
    ["MATH 244", "Sophomore", 3, "No", "Neither", 2],
    ["PHYS 151", "Sophomore", 3, "No", "Neither", 3],
    ["EDUC 402", "Junior", 3, "No", "Neither", 2],
    ["EDUC 403", "Junior", 3, "No", "Wrting", 2],
    ["EDUC 308", "Junior", 3, "No", "Reading", 1],
    ["CSCI 201", "Junior", 3, "No", "Neither", 4],
    ["CSCI 330B", "Junior", 3, "No", "Neither", 4],
    ["SPAN 101", "Junior", 3, "No", "Both", 2],
    ["CSCI 200", "Freshman", 3, "No", "Neither", 2],
    ["COMM 120", "Freshman", 3, "No", "Neither", 1],
    ["INST 150", "Freshman", 3, "No", "Neither", 1],
    ["CSCI 175", "Freshman", 3, "No", "Neither", 3],
    ["MATH 221", "Freshman", 3, "No", "Neither", 4],
    ["BIBL 200", "Freshman", 3, "No", "Neither", 2],
    ["DTSC 220", "Freshman", 3, "No", "Neither", 5],
    ["CSCI 200", "Freshman", 3, "No", "Neither", 2],
    ["MATH 160", "Freshman", 3, "No", "Neither", 3],
    ["BIOL 233L", "Sophomore", 3, "Yes", "Reading", 6],
    ["CSCI 201", "Sophomore", 3, "No", "Neither", 6],
    ["NURS 220", "Sophomore", 3, "No", "Reading", 3],
    ["CSCI 405", "Sophomore", 3, "No", "Neither", 6],
    ["EXSC 201", "Sophomore", 3, "No", "Neither", 0],
    ["ENGL 102", "Freshman", 3, "No", "Both", 5],
    ["MATH 161", "Freshman", 3, "No", "Neither", 3],
    ["DTSC 250", "Sophomore", 3, "No", "Neither", 1],
    ["DTSC 320", "Senior", 3, "No", "Neither", 7],
    ["CSCI 250", "Sophomore", 3, "No", "Neither", 4],
    ["MATH 240", "Freshman", 3, "No", "Neither", 2],
    ["BUSA 221", "Sophomore", 3, "No", "Neither", 2],
    ["MATH 240", "Freshman", 3, "No", "Neither", 3],
    ["FINA 350", "Junior", 3, "No", "Neither", 8],
    ["CSCI 310", "Sophomore", 3, "No", "Neither", 2],
    ["CSCI 325", "Junior", 3, "No", "Neither", 4],
    ["MKTG 202", "Freshman", 3, "No", "Both", 3],
    ["CSCI 410", "Junior", 3, "No", "Neither", 4],
    ["CSCI 320", "Junior", 3, "No", "Neither", 4],
    ["HIST 160", "Junior", 3, "No", "Reading", 4],
    ["COMM 120", "Junior", 3, "No", "Neither", 2],
    ["HIST 160", "Sophomore", 3, "No", "Reading", 4],
    ["CHEM 211", "Sophomore", 3, "No", "Neither", 3],
    ["CHEM 231", "Sophomore", 3, "No", "Neither", 3],
    ["COMM 120", "Junior", 3, "No", "Neither", 1],
    ["MATH 221", "Sophomore", 3, "No", "Neither", 1],
    ["INST 150", "Freshman", 3, "No", "Neither", 2],
    ["CHEM 231L", "Sophomore", 1, "Yes", "Wrting", 2],
    ["LDEV 200", "Sophomore", 3, "No", "Both", 2],
    ["MATH 330", "Junior", 3, "No", "Neither", 2],
    ["CHEM 231W", "Sophomore", 1, "Yes", "Wrting", 3],
    ["HIST 372", "Sophomore", 3, "No", "Both", 4],
    ["MATH 414", "Junior", 3, "No", "Wrting", 2],
    ["CSCI 410", "Sophomore", 3, "No", "Neither", 2],
    ["SOWK 110", "Sophomore", 3, "No", "Reading", 1],
    ["SPAN 101", "Sophomore", 3, "No", "Both", 1],
    ["HIST 160", "Sophomore", 3, "No", "Reading", 2],
    ["MKTG 202", "Sophomore", 3, "No", "Both", 2],
    ["ECON 203", "Sophomore", 3, "No", "Both", 1],
    ["CSCI 201", "Sophomore", 3, "No", "Neither", 2],
    ["ENGL 102", "Freshman", 3, "No", "Wrting", 8],
    ["PSYC 340W", "Sophomore", 3, "No", "Wrting", 8],
    ["ENGL 235", "Sophomore", 3, "No", "Reading", 2],
    ["PSYC 220", "Sophomore", 3, "No", "Neither", 1],
    ["PSYC 318", "Sophomore", 3, "No", "Both", 3],
    ["DTSC 220", "Freshman", 3, "No", "Neither", 1],
    ["CSCI 320", "Sophomore", 3, "No", "Neither", 3],
    ["COMM 220", "Sophomore", 3, "No", "Neither", 1],
    ["HONR 330", "Junior", 1, "No", "Neither", 1],
    ["THEO 210", "Freshman", 3, "No", "Neither", 2],
    
]

In [3]:

columns = ["Course Code", "Year", "Credits", "Has Writing", "Preference", "Aprox Time"]
df = pd.DataFrame(data, columns=columns)

df["Credits"] = pd.to_numeric(df["Credits"])
df["Aprox Time"] = pd.to_numeric(df["Aprox Time"])

In [5]:
Average_df = df.groupby("Course Code").agg({
    "Year": lambda x: x.mode().iloc[0],
    "Credits": "mean",
    "Has Writing": lambda x: x.mode().iloc[0],
    "Preference": lambda x: x.mode().iloc[0],
    "Aprox Time": "mean"
}).reset_index()

Average_df["Aprox Time"] = Average_df["Aprox Time"].round(0)

print("Average Of All Data For Each Class:")

Average Of All Data For Each Class:
   Course Code       Year  Credits Has Writing Preference  Aprox Time
0     BIBL 200   Freshman      3.0          No    Neither         2.0
1    BIOL 233L  Sophomore      3.0         Yes    Reading         6.0
2     BUSA 221  Sophomore      3.0          No    Neither         2.0
3     CHEM 211  Sophomore      3.0          No    Neither         3.0
4     CHEM 231  Sophomore      3.0          No    Neither         3.0
5    CHEM 231L  Sophomore      1.0         Yes     Wrting         2.0
6    CHEM 231W  Sophomore      1.0         Yes     Wrting         3.0
7     COMM 120     Junior      3.0          No    Neither         1.0
8     COMM 220  Sophomore      3.0          No    Neither         1.0
9     CSCI 175   Freshman      3.0          No    Neither         1.0
10    CSCI 200   Freshman      3.0          No    Neither         2.0
11    CSCI 201  Sophomore      3.0          No    Neither         4.0
12    CSCI 250  Sophomore      3.0          No    Neither         4.0
13    CSCI 310  Sophomore      3.0          No    Neither         2.0
14    CSCI 320     Junior      3.0          No    Neither         4.0
15    CSCI 325     Junior      3.0          No    Neither         4.0
16   CSCI 330B     Junior      3.0          No    Neither         4.0
17    CSCI 405     Senior      3.0          No    Neither         4.0
18    CSCI 410     Junior      3.0          No    Neither         3.0
19    DTSC 220   Freshman      3.0          No    Neither         3.0
20    DTSC 250  Sophomore      3.0          No    Neither         1.0
21    DTSC 320     Senior      3.0          No    Neither         4.0
22    DTSC 380     Senior      3.0          No    Neither         1.0
23    ECON 203  Sophomore      3.0          No       Both         1.0
24    EDUC 308     Junior      3.0          No    Reading         1.0
25    EDUC 402     Junior      3.0          No    Neither         2.0
26    EDUC 403     Junior      3.0          No     Wrting         2.0
27    ENGL 102   Freshman      3.0          No       Both         5.0
28    ENGL 235  Sophomore      3.0          No    Reading         2.0
29    EXSC 201  Sophomore      3.0          No    Neither         0.0
30    FINA 350     Junior      3.0          No    Neither         8.0
31    HIST 160  Sophomore      3.0          No    Reading         3.0
32    HIST 372  Sophomore      3.0          No       Both         4.0
33    HONR 330     Junior      1.0          No    Neither         1.0
34    INST 150   Freshman      3.0          No    Neither         1.0
35    LDEV 200  Sophomore      3.0          No       Both         2.0
36    MATH 160   Freshman      3.0          No    Neither         2.0
37    MATH 161   Freshman      3.0          No    Neither         3.0
38    MATH 221   Freshman      3.0          No    Neither         2.0
39    MATH 240   Freshman      3.0          No    Neither         2.0
40    MATH 244  Sophomore      3.0          No    Neither         2.0
41    MATH 330     Junior      3.0          No    Neither         2.0
42    MATH 414     Junior      3.0          No     Wrting         2.0
43    MISS 100  Sophomore      3.0          No    Reading         2.0
44    MKTG 202   Freshman      3.0          No       Both         2.0
45    MUSI 145     Senior      2.0          No    Neither         1.0
46    Math 107     Junior      3.0          No     Wrting         3.0
47    Math 160   Freshman      3.0          No    Neither         3.0
48    NURS 220  Sophomore      3.0          No    Reading         3.0
49    PHYS 151  Sophomore      3.0          No    Neither         3.0
50    PSYC 220  Sophomore      3.0          No    Neither         1.0
51    PSYC 318  Sophomore      3.0          No       Both         3.0
52   PSYC 340W  Sophomore      3.0          No     Wrting         8.0
53    Psyc 205  Sophomore      3.0          No    Neither         8.0
54    SOWK 110  Sophomore      3.0          No    Reading         0.0
55    SPAN 101     Junior      3.0          No       Both         2.0
56    THEO 210   Freshman      3.0          No    Neither         2.0

In [11]:
# Assuming df is your DataFrame and 'your_column' is the column you want to process
course_codes = df['Course Code'].astype(str).str[:4].unique()
course_codes.sort()
course_codes = pd.DataFrame(course_codes)
course_codes

       0
0   BIBL
1   BIOL
2   BUSA
3   CHEM
4   COMM
5   CSCI
6   DTSC
7   ECON
8   EDUC
9   ENGL
10  EXSC
11  FINA
12  HIST
13  HONR
14  INST
15  LDEV
16  MATH
17  MISS
18  MKTG
19  MUSI
20  Math
21  NURS
22  PHYS
23  PSYC
24  Psyc
25  SOWK
26  SPAN
27  THEO

In [14]:
#writing the dataFrames to csv files

#depatment codes
course_codes.to_csv("department_codes.csv")

# everything else
Average_df.to_csv("course_data.csv")